# Generated by Django 4.2.16 on 2024-09-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maxtemp_c', models.FloatField()),
                ('maxtemp_f', models.FloatField()),
                ('mintemp_c', models.FloatField()),
                ('mintemp_f', models.FloatField()),
                ('avgtemp_c', models.FloatField()),
                ('avgtemp_f', models.FloatField()),
                ('maxwind_mph', models.FloatField()),
                ('maxwind_kph', models.FloatField()),
                ('totalprecip_mm', models.FloatField()),
                ('totalprecip_in', models.FloatField()),
                ('avghumidity', models.IntegerField()),
                ('condition_text', models.CharField(max_length=100)),
                ('condition_icon', models.URLField()),
                ('condition_code', models.IntegerField()),
                ('uv', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(max_length=50)),
                ('localtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('temp_f', models.FloatField()),
                ('is_day', models.BooleanField()),
                ('condition_text', models.CharField(max_length=100)),
                ('condition_icon', models.URLField()),
                ('condition_code', models.IntegerField()),
                ('wind_mph', models.FloatField()),
                ('wind_kph', models.FloatField()),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('pressure_mb', models.FloatField()),
                ('pressure_in', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('precip_in', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('feelslike_c', models.FloatField()),
                ('feelslike_f', models.FloatField()),
                ('gust_mph', models.FloatField()),
                ('gust_kph', models.FloatField()),
                ('uv', models.FloatField()),
                ('forecast_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.forecastday')),
            ],
        ),
        migrations.AddField(
            model_name='forecastday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.location'),
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('temp_c', models.FloatField()),
                ('temp_f', models.FloatField()),
                ('is_day', models.BooleanField()),
                ('condition_text', models.CharField(max_length=100)),
                ('condition_icon', models.URLField()),
                ('condition_code', models.IntegerField()),
                ('wind_mph', models.FloatField()),
                ('wind_kph', models.FloatField()),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=10)),
                ('pressure_mb', models.FloatField()),
                ('pressure_in', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('precip_in', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('feelslike_c', models.FloatField()),
                ('feelslike_f', models.FloatField()),
                ('uv', models.FloatField()),
                ('gust_mph', models.FloatField()),
                ('gust_kph', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.location')),
            ],
        ),
    ]
