from django.db import models

# Create your models here.

class Location(models.Model):
    name = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()
    timezone = models.CharField(max_length=50)
    localtime = models.DateTimeField()

class CurrentWeather(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    last_updated = models.DateTimeField()
    temp_c = models.FloatField()
    temp_f = models.FloatField()
    is_day = models.BooleanField()
    condition_text = models.CharField(max_length=100)
    condition_icon = models.URLField()
    condition_code = models.IntegerField()
    wind_mph = models.FloatField()
    wind_kph = models.FloatField()
    wind_degree = models.IntegerField()
    wind_dir = models.CharField(max_length=10)
    pressure_mb = models.FloatField()
    pressure_in = models.FloatField()
    precip_mm = models.FloatField()
    precip_in = models.FloatField()
    humidity = models.IntegerField()
    cloud = models.IntegerField()
    feelslike_c = models.FloatField()
    feelslike_f = models.FloatField()
    uv = models.FloatField()
    gust_mph = models.FloatField()
    gust_kph = models.FloatField()

class ForecastDay(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    date = models.DateField()
    maxtemp_c = models.FloatField()
    maxtemp_f = models.FloatField()
    mintemp_c = models.FloatField()
    mintemp_f = models.FloatField()
    avgtemp_c = models.FloatField()
    avgtemp_f = models.FloatField()
    maxwind_mph = models.FloatField()
    maxwind_kph = models.FloatField()
    totalprecip_mm = models.FloatField()
    totalprecip_in = models.FloatField()
    avghumidity = models.IntegerField()
    condition_text = models.CharField(max_length=100)
    condition_icon = models.URLField()
    condition_code = models.IntegerField()
    uv = models.FloatField()

class HourlyForecast(models.Model):
    forecast_day = models.ForeignKey(ForecastDay, on_delete=models.CASCADE)
    time = models.DateTimeField()
    temp_c = models.FloatField()
    temp_f = models.FloatField()
    is_day = models.BooleanField()
    condition_text = models.CharField(max_length=100)
    condition_icon = models.URLField()
    condition_code = models.IntegerField()
    wind_mph = models.FloatField()
    wind_kph = models.FloatField()
    wind_degree = models.IntegerField()
    wind_dir = models.CharField(max_length=10)
    pressure_mb = models.FloatField()
    pressure_in = models.FloatField()
    precip_mm = models.FloatField()
    precip_in = models.FloatField()
    humidity = models.IntegerField()
    cloud = models.IntegerField()
    feelslike_c = models.FloatField()
    feelslike_f = models.FloatField()
    gust_mph = models.FloatField()
    gust_kph = models.FloatField()
    uv = models.FloatField()

